version: '3.1'
services:
  web:
    build: ./
    hostname: redisLab
    ports:
      - "81:44302"
    links:
      - redis:labRedis
    depends_on:
      - redis
    networks: 
      - redisLab_network
  redis:
    hostname: RedisDevServer
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - redisLab_network

networks: 
  redisLab_network: {} 