version: '3.1'
services:
  web:
    build: ./RedisLab
    hostname: redisLab
    ports:
      - "5000:5000"
    links:
      - redis:labRedis
    depends_on:
      - redis
  redis:
    hostname: labRedis
    image: redis
    ports:
      - "6379:6379"